// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shared.Models;

#nullable disable

namespace Shared.Migrations
{
    [DbContext(typeof(CompanyData))]
    [Migration("20240119123040_AddedMarketCapitalizationAPILimit")]
    partial class AddedMarketCapitalizationAPILimit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shared.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CIK")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CashAndCashEquivalents")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("EmployedCapital")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal>("EnterpriseValue")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<string>("Exchange")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastFilingDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("LastMarketCapitalization")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<DateTime?>("LastMarketCapitalizationDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("NetCurrentAssets")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal>("OperatingIncome")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<float>("OperatingIncomeToEnterpriseValue")
                        .HasColumnType("real");

                    b.Property<decimal>("PropertyPlantAndEquipment")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<float>("ReturnOnEmployedCapital")
                        .HasColumnType("real");

                    b.Property<string>("Ticker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalDebt")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Shared.Models.Fmp", b =>
                {
                    b.Property<string>("ApiKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastDay")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxRequestsPerDay")
                        .HasColumnType("int");

                    b.Property<DateTime>("MinimumTimeUpdateMarketCapitalizations")
                        .HasColumnType("datetime2");

                    b.Property<int>("RequestsToday")
                        .HasColumnType("int");

                    b.ToTable("Fmp");
                });
#pragma warning restore 612, 618
        }
    }
}
